### ISSUE TITLE
Unable to save project

### ISSUE THREAD

**Issue by weitzhandler** [tunnelvisionlabs/LangSvcV2#13]
My IDE is set so that when a project is created, it doesn't get saved immediately, giving me a way to discard projects without leaving them on my computer.

Anyway when I create a new Java console app, I get the following error message:

> Unable to locate the solution directory. Please ensure that the solution has been saved.

I believe this happens because the project is created in some unknown temp folder elsewhere in the system.
The project is created, but then when I attempt to save it I get this error:

> The operation could not be completed

Please fix this, and if you have a chance, please comment on, so I get notified.

**Comment by sharwell** [comment]
I'm not sure this is possible with the Java project system. In order to distribute the entire build system and debugger in a single VSIX file, the extension uses NuGet to install the compiler features into the project after the project is created. NuGet expects the project to exist on disk in order to install packages.

**Comment by sharwell** [comment]
Interesting. It seems the [CreateInPlace](http://msdn.microsoft.com/en-us/library/ms247196.aspx) and/or [PromptForSaveOnCreation](http://msdn.microsoft.com/en-us/library/twfxayz5.aspx) elements of the project template may be able to override the IDE setting you refer to, *forcing* the project to be saved when created. While this does not give you exactly the behavior you want, it would prevent the errors from appearing.

**Comment by sharwell** [comment]
I just tested this and setting the **PromptForSaveOnCreation** element to true forces the New Project dialog to prompt the user for a location in which to save the project. :+1:
