### ISSUE TITLE
Classpath modification

### ISSUE THREAD

**Issue by sriksrid** [tunnelvisionlabs/LangSvcV2#45]
Hi

I noticed that when I debug/run a file, a classpath is being specified (the jar file built), and this is causing my existing classpath to be ignored (I even added an extra cp command to the command line options, but that doesn't work either). Is there I way I can append entries to the classpath override for debug/run? I'm willing to edit the configuration files, if necessary. 

The build works fine if I specify the libraries in References; however they do not get carried over to debug - which is why I want to modify the classpath.

Thank you

**Comment by sharwell** [comment]
Hi @sriksrid,

Thank you for taking time to report this. I believe this was fixed in one of my experimental branches (specifically commit b2abfcdb1c4c9d4dc86a5d1879c3180a15236b0d). I intend for a solution to this to be available for the next release.

**Comment by sharwell** [comment]
Hi @sriksrid,

Today I separated the Java support extension from this repository to make it easier for the community to get involved with the project. I moved this issue to the new repository; you can find it at tunnelvisionlabs/JavaForVS#14. The **invalid** label you see just means *this* issue is now in the wrong repository (even though it was correct when you posted it).

Thanks again for reporting the issue, and you should see a new release very soon containing this fix. :+1:
