### ISSUE TITLE
About Java for Visual Studio support

### ISSUE THREAD

**Issue by Joe12323231** [tunnelvisionlabs/LangSvcV2#46]
I want to talk about Java for Visual Studio. The intellisense doesn't work, you know the auto corrections and auto fill that sort of stuff, did I not install it correctly or what?

**Comment by sharwell** [comment]
The extension does not currently support these features. The focus to date has been on debugging support, with only minimal work on the editor features (such as basic syntax highlighting and outlining). Please feel free to open requests for specific features, but keep in mind that the project is moving along *very* slowly aside from the recent work on expanding the debugger functionality.
