### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by LuizZak** [tunnelvisionlabs/LangSvcV2#55]
Are there any plans to add support for the newest VS 2015 RC? I've added the Antlr4 dependencies to my project, but most of the build steps described at https://github.com/tunnelvisionlabs/antlr4cs/blob/master/Readme.md require the extension (or maybe I'm missing something?), and I'm kinda stuck now, can't compile my project because it's not compatible with the older parser I generated with the IntelliJ plugin.

Thanks.

**Comment by sharwell** [comment]
Hi @LuizZak,

> Are there any plans to add support for the newest VS 2015 RC?

There are now! :smile: 

Would you be available to test a couple of things for me before I make a release? If so, the best place to join me is either the [Gitter room for this repository](https://gitter.im/tunnelvisionlabs/LangSvcV2) or the [Gitter room for the ANTLR C# Target](https://gitter.im/tunnelvisionlabs/antlr4cs).

**Comment by LuizZak** [comment]
Sure thing
