### ISSUE TITLE
Not working with VS 2015 CE

### ISSUE THREAD

**Issue by bibilemihai** [tunnelvisionlabs/LangSvcV2#62]
14/08/2015 14:21:44 - Microsoft VSIX Installer
14/08/2015 14:21:44 - -------------------------------------------
14/08/2015 14:21:45 - Initializing Install...
14/08/2015 14:21:45 - Détails de l'extension...
14/08/2015 14:21:45 - 	Identifier      : Tvl.VisualStudio.Language.Php.ece72f50-0b6f-4363-9986-e38af13f6aa5
14/08/2015 14:21:45 - 	Name            : PHP Language Support
14/08/2015 14:21:45 - 	Author          : Sam Harwell
14/08/2015 14:21:45 - 	Version         : 1.1.0
14/08/2015 14:21:45 - 	Description     : Basic support for the PHP programming language.
14/08/2015 14:21:45 - 	Locale          : en-US
14/08/2015 14:21:45 - 	MoreInfoURL     : 
14/08/2015 14:21:45 - 	InstalledByMSI  : False
14/08/2015 14:21:45 - 	SupportedFrameworkVersionRange : [4.0,)
14/08/2015 14:21:45 - 
14/08/2015 14:21:45 - 	Produits pris en charge : 
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Ultimate
14/08/2015 14:21:45 - 			Version : [10.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Ultimate
14/08/2015 14:21:45 - 			Version : [11.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Ultimate
14/08/2015 14:21:45 - 			Version : [12.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Premium
14/08/2015 14:21:45 - 			Version : [10.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Premium
14/08/2015 14:21:45 - 			Version : [11.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Premium
14/08/2015 14:21:45 - 			Version : [12.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Pro
14/08/2015 14:21:45 - 			Version : [10.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Pro
14/08/2015 14:21:45 - 			Version : [11.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.Pro
14/08/2015 14:21:45 - 			Version : [12.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.IntegratedShell
14/08/2015 14:21:45 - 			Version : [10.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.IntegratedShell
14/08/2015 14:21:45 - 			Version : [11.0]
14/08/2015 14:21:45 - 		Microsoft.VisualStudio.IntegratedShell
14/08/2015 14:21:45 - 			Version : [12.0]
14/08/2015 14:21:45 - 
14/08/2015 14:21:45 - 	Références      : 
14/08/2015 14:21:45 - 		-------------------------------------------------------
14/08/2015 14:21:45 - 		Identifier   : Tvl.VisualStudio.Framework.922dc49e-a1f8-43c2-a748-504c676ebbb6
14/08/2015 14:21:45 - 		Name         : Visual Studio Extensibility Framework
14/08/2015 14:21:45 - 		Version      : [1.2.0,)
14/08/2015 14:21:45 - 		MoreInfoURL  : 
14/08/2015 14:21:45 - 		Nested       : Yes
14/08/2015 14:21:45 - 
14/08/2015 14:21:45 - 
14/08/2015 14:21:45 - Recherche des produits applicables...
14/08/2015 14:21:45 - Produit installé trouvé - Microsoft Visual Studio Community 2015
14/08/2015 14:21:45 - Produit installé trouvé - Microsoft Visual Studio 2015 Shell (Integrated)
14/08/2015 14:21:45 - Produit installé trouvé - Emplacement global
14/08/2015 14:21:45 - VSIXInstaller.NoApplicableSKUsException: Cette extension n'est installée sur aucun des produits actuellement installés.
   à VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   à VSIXInstaller.App.InitializeInstall()
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()

**Comment by sharwell** [comment]
Hi @bibilemihai,

I added an explanation for the current state of Visual Studio 2015 support in #63. I'm going to mark this as a duplicate (even though you reported it first) just so I can track the feature in one place.

Thank you for taking time to write up this issue report, and I hope I can get this functionality delivered sooner rather than later. :smile:
