### ISSUE TITLE
VS2017 support

### ISSUE THREAD

**Issue by b3b00** [tunnelvisionlabs/LangSvcV2#80]
Do you plan to port your extension to Visual Studio 2017 any soon ?

**Comment by cjbush** [comment]
https://github.com/tunnelvisionlabs/LangSvcV2/pull/81

Ask and you shall receive.

**Comment by cjbush** [comment]
Note that I haven't actually tried it out to see if it works. I just updated the files to allow you to install it in VS2017.

**Comment by kintoshmalae** [comment]
Any further word of a release date on this? The current download will not install into VS2017 at the moment.

**Comment by jamesqo** [comment]
Would also like to be able to install ANTLR 4 support in VS2017.

**Comment by sharwell** [comment]
This was blocked on tunnelvisionlabs/vsbase#56 for a long time but it shouldn't be any longer.

**Comment by sharwell** [comment]
An initial pull request is available in #83. I have a few more things left to do, but it seems to work if you manually download the VSIX file(s) of interest attached to the AppVeyor build. (Please provide feedback if you try this and you notice anything not working.)
