### ISSUE TITLE
ANTLR templates do not appear in new project system

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/LangSvcV2#84]
:link: Originally reported by @jamesqo in https://github.com/tunnelvisionlabs/LangSvcV2/pull/83#issuecomment-309955557.

**Comment by sebandraos** [comment]
Might this have to do with this old issue https://github.com/tunnelvisionlabs/LangSvcV2/issues/61?

**Comment by sharwell** [comment]
It actually turned out that the templates were mostly fine. In my first attempt to reproduce the problem, I wasn't able to because I was using the new project system to target `net45`. However, when I changed to `netstandard1.3`, the templates disappeared.

As I often do when examining template issues, I went and found one of the template files which still appeared in .NET Standard projects and opened its definition:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ItemTemplates\CSharp\Code\1033\Class\Class.vstemplate
```

Comparing this to the templates for ANTLR, it was immediately clear where the difference lied.

**Comment by kappa7194** [comment]
I downloaded the `Tvl.VisualStudio.Tools.Antlr.vsix` file from [build 1.0.44](https://ci.appveyor.com/project/sharwell/langsvcv2/build/1.0.44/artifacts) and installed it in Visual Studio Professional 2017 (15.2.0+26430.15) and the extension [seems to be enabled](https://user-images.githubusercontent.com/1249988/28271892-28fc5e78-6b0a-11e7-8ed5-cc0b93e15d7c.png), but I'm unable to find the templates even for non-Core projects, I don't even have the "ANTLR" category in the add file pop-up. Am I missing something?

![Add New Item pop-up](https://user-images.githubusercontent.com/1249988/28272124-d44b7bec-6b0a-11e7-9d93-e21cfd91a1d3.png)

**Comment by sharwell** [comment]
@kappa7194 Try uninstalling the extension, restarting Visual Studio, and then installing it again from the VSIX.

**Comment by kappa7194** [comment]
> Try uninstalling the extension, restarting Visual Studio, and then installing it again from the VSIX.

Found the problem, my fault: I downloaded and installed `Tvl.VisualStudio.Tools.Antlr.vsix` instead of `Tvl.VisualStudio.Language.Antlr3.vsix`.
