### ISSUE TITLE
NestedExtensionInstallExeption while installation

### ISSUE THREAD

**Issue by vsdeer** [tunnelvisionlabs/LangSvcV2#90]
Hello,
I get an NestedExtensionInstallExeption that tell me that one element key is already used. Sorry but I am not familiar with VS Extensions and I can't handle that message . Can I clean up the extension keys, or how can I fix or work around that issue. I need this extension for a project which is depending on antlr. I attach the error log.

Thank you in advance

[VSIXInstaller_55106cea-2b74-4d5c-8f3b-f2e579482017.log](https://github.com/tunnelvisionlabs/LangSvcV2/files/1472768/VSIXInstaller_55106cea-2b74-4d5c-8f3b-f2e579482017.log)

**Comment by sharwell** [comment]
This should be fixed now. The Output Window extension version 3.1.0 dropped support for Visual Studio 2010, which is where the exception was being thrown.
